name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Install library dependencies
      run: pio lib -g install ArduinoJson@7.3.1

    - name: Run PlatformIO
      run: pio ci --lib="." --project-option="framework=espidf" --board=esp32dev
      env:
        PLATFORMIO_CI_SRC: examples/main.cpp
